spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout:
      password:
      jedis.pool.max-active: 100
      jedis.pool.max-wait: -1
      jedis.pool.max-idle: 100
      jedis.pool.min-idle: 0
  application:
    name: aj

demo.client.bean: